export type geoCodingType = {
  place_id: number;
  licence: string;
  osm_type: string;
  osm_id: number;
  lat: string;
  lon: string;
  category: string;
  type: string;
  place_rank: number;
  importance: number;
  addressType: string;
  name: string;
  display_name: string;
  address: {
    road: string;
    suburb: string;
    city: string;
    town?: string;
    village?: string;
    county: string;
    state_district: string;
    state: string;
    "ISO3166-2-1v14": string;
    postcode: string;
    country: string;
    country_code: string;
  };
  boundingbox: string[];
};